### ISSUE TITLE
Unable to connect with self-signed certificates

### ISSUE THREAD

**Issue by yoavnash** [MI-FraunhoferIWM/dsms-python-sdk#13]
When developing the DSMS locally, we're using a self-signed certificate which the SDK doesn't accept.

Copied from https://github.com/MI-FraunhoferIWM/dsms-sdk/issues/4

**Comment by MBueschelberger** [comment]
This is already solved in v1.3.3:

https://github.com/MI-FraunhoferIWM/dsms-python-sdk/blob/f7d0d5e02c2e838f4808baff08afb3df50c296ce/dsms/core/configuration.py#L36

**Comment by yoavnash** [comment]
I just checked and it still fails for me. It seems this parameter is not being used here: https://github.com/MI-FraunhoferIWM/dsms-python-sdk/blob/62d9d37da82b344c4ca6db5a420062a8692ada8c/dsms/core/configuration.py#L110
